### ISSUE TITLE
Can't upload example refpolicy

### ISSUE THREAD

**Issue by mykter** [invincealabs/V3SPA#1]
When I try and drop the provided example refpolicy or occam policy, it reports:

> Reference policy must be uploaded as a zipfile

There doesn't appear to be any option to specify the file other than via drag and drop.

Chrome 52, Windows 7, vagrant install. Manually started the server.

I noticed one error during install:
`npm ERR! version not found: esprima-six@0.0.3`

**Comment by rpgove** [comment]
I don't immediately see why that would happen. That error on install shouldn't affect anything. At first glance, the browser might not be detecting the upload file as a zip. I can try some other tests later. Just to confirm, you're uploading one of the zip files in the /policy-examples/ directory, right?

**Comment by mykter** [comment]
Correct

**Comment by rpgove** [comment]
Looks like the zip mimetype is different on Windows. I pushed a new commit that should fix this: 28e7700d451ebcf8a816b071b77ff3d8365070d7

Please pull this new version and let me know if you continue to have issues.
