### ISSUE TITLE
Lobster can't parse REQUIRE elements

### ISSUE THREAD

**Issue by mykter** [invincealabs/V3SPA#2]
When uploading a policy (not one of the provided examples), I get the following error:

> Unable to import policy: backend:lobster - A web handler threw an exception. Details: user error (./refpolicy/refpolicy/policy/modules/contrib/example.te: parser error: Parse error at T (Pos "./refpolicy/refpolicy/policy/modules/contrib/example.te" 1053 58 1) REQUIRE)

This is the policy file from line 58:

``` selinux
require {
        type bin_t;
        type console_device_t;
        type devpts_t;
        ... more types
        class blk_file { create setattr getattr unlink  create setattr };
        ... more classes
}
```

**Comment by rpgove** [comment]
Looks like this is actually an issue with [Lobster](https://github.com/invincealabs/lobster). I asked one of its main developers (@jamesjb) to take a look at this and see if he has any insights.

In the meantime, are you able to build your policy and import just the binary of your policy?

**Comment by mykter** [comment]
In building the policy outside of the build system it is normally built in I ran into the same issue lobster did, so this probably isn't lobster's problem.
I'll raise a separate issue for the problem I've run into using the binary.
