### ISSUE TITLE
Upload zip format instructions are confusing

### ISSUE THREAD

**Issue by mykter** [invincealabs/V3SPA#3]
The format for uploading a binary policy is 
`<zipname>.zip` containing the structure: `<zipname>/policy/sepolicy`
I couldn't work this out from the instructions, only looking in one of the provided instructions. Suggest adding an example to the README and the error message when uploading a zip.

(but I have now got my policy loaded and will have a play, thanks for the tool!)

**Comment by rpgove** [comment]
Thanks for your feedback! I added more detailed instructions to the README and the error message. Please let me know if you have any other feedback.
