### ISSUE TITLE
Containerised version of the tool

### ISSUE THREAD

**Issue by sammcj** [invincealabs/V3SPA#5]
It would be neat if you could run this tool in a container from an image.

This would remove the need to have a special Fedora 24 install specifically to run it and for people running macOS on their workstation to test locally created SELinux policies before moving to testing them on VMs / remote systems.

**Comment by rpgove** [comment]
I agree this would be a great addition! That was the idea with Vagrant, but it's not as smooth as a Docker container could be. Unfortunately I don't have time to implement this feature now, but please feel free to submit a pull request if you implement this feature yourself.

**Comment by tcagan** [comment]
Hi,
There's a PR (#7) for adding docker support.
Not sure if this project is active and there is someone who can merge it.
You can give it a try and comment on the PR in case changes are required.
